- Implementations.md
- README.md
This will be a place for developers to let everyone know of
their pygls-based implementation.
> Add Implementations.md

- CHANGELOG.md
- docs/source/index.rst
- docs/source/pages/advanced_usage.rst
- docs/source/pages/tutorial.rst
- examples/README.md
- examples/json-extension/client/package-lock.json
- examples/json-extension/client/package.json
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- examples/json-extension/server/server.py
- examples/json-extension/server/tests/unit/test_features.py
- pygls/server.py
- setup.py
> release 0.7.1

- CHANGELOG.md
- appveyor.yml
- examples/json-extension/client/package-lock.json
- examples/json-extension/client/package.json
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- pygls/exceptions.py
- pygls/protocol.py
- pygls/server.py
- pygls/types.py
- pygls/uris.py
- pygls/workspace.py
- setup.cfg
- setup.py
- tests/test_language_server.py
- tests/test_protocol.py
> Refactor LSP initialize method

- CHANGELOG.md
- examples/json-extension/client/package-lock.json
- examples/json-extension/client/package.json
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- setup.py
> Release v0.7.4

- CHANGELOG.md
- tests/test_protocol.py
Small PR to increase test coverage for deserialize_message function.
> Add more tests for deserialize_message function

- CHANGELOG.md
- appveyor.yml
- examples/json-extension/client/package-lock.json
- examples/json-extension/client/package.json
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- setup.py
> Release v0.8.0

- appveyor.yml
- examples/json-extension/client/package-lock.json
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
This PR updates npm dependencies due to following security issue:
`Upgrade diff to version 3.5.0 or later`
> Update json-example npm dependencies

- Implementations.md
I wrote a simple, constrained Python Language Server implementation over the weekend using pygls. Since I could find no easy examples for how to do this online (besides the simple JSON example in this repo), I figure this implementation could help more people get the most out of pygls.
I'll be continuing to develop jedi-language-server / using it in my daily workflow, so expect comments / feedback as I learn more about LSP and add more configurations / features. Thanks for the great library; it made writing my language server fairly simple.
> Add "Jedi Language Server" to Implementations.md

- CHANGELOG.md
- examples/json-extension/client/package-lock.json
- examples/json-extension/client/package.json
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- setup.py
> Update changelog and versions

- Implementations.md
I packaged this lsp on the [aur](https://aur.archlinux.org/packages/cmake-language-server/).
It only has basic functionality (No include() completion, no go definition, no go reference, etc)
> Add cmake language server to Implementations.md

- pygls/protocol.py
- pygls/server.py
See https://github.com/openlawlibrary/pygls/issues/93
> Fix some typing errors reported by mypy

- CHANGELOG.md
- pygls/types.py
This member was wrongly named FailureHandlingKind.FailureHandlingKind
Fixes #95
> types: fix FailureHandlingKind.Undo

- examples/json-extension/package-lock.json
- examples/json-extension/package.json
Update json-example npm packages due to "potential security vulnerability".
> Update json-example npm packages

- pygls/types.py
Updated according to the current LSP specification
https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-15.md#textDocument_documentSymbol
> Updated SymbolKinds

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- setup.py
> Release v0.9.0

- examples/json-extension/server/server.py
- pygls/protocol.py
> Fix some typos

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- setup.py
> Release v0.9.1

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/exceptions.py
- pygls/protocol.py
- tests/test_protocol.py
Closes #126.
I just cherry-picked commits and resolved conflicts from PR #141.
> Fix jsonrpc error

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- setup.py
> Release v0.10.0

- .editorconfig
> Added .editorconfig according to PEP8

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- setup.py
- tests/test_server_connection.py
Updated versions and the changelog.
> Release v0.10.2

- README.md
Recent changes made the example code invalid. I replaced the problematic imports with their new names.
> fix imports for the quick intro example code

- pygls/protocol.py
- pygls/server.py
> Handler BrokenPipeError on shutdown

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
- Bump version
- Update changelog
> Release v0.10.3

- .github/workflows/ci.yml
- CHANGELOG.md
- setup.cfg
- tox.ini
Update Tox and GitHub Actions to test against Python 3.9. Also add the appropriate trove classifier.
Required updating mypy.
Closes #186 
> Test against Python 3.9

- pyproject.toml
- setup.cfg
> Added the build deps to setup.cfg to make setuptools to update themselves if needed and install other build dependencies.

- pygls/protocol.py
> Use builtin features when creating server cap

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
> Release v0.11.0

- pygls/protocol.py
> Add back accidentally removed default_serializer

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
> Release v0.11.1

- pygls/feature_manager.py
- tests/__init__.py
- tests/ls_setup.py
- tests/test_language_server.py
Fix adding help attributes to registered feature/command handlers.
This fix makes sure that [this](https://github.com/openlawlibrary/pygls/blob/master/pygls/protocol.py#L206) piece of code is properly executed and handler's return values are type-checked.
> Fix feature manager

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
> Release v0.11.2

- CHANGELOG.md
- CONTRIBUTORS.md
- examples/json-extension/client/src/extension.ts
Update example extension to detect debug mode better
> Update example extension to detect debug mode better

- .github/workflows/json-extension.yml
- examples/json-extension/LICENSE.txt
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
Fix json extension build pipeline.
> Fix how semantic tokens server capabilities are computed (#213)

- CHANGELOG.md
- examples/json-extension/package-lock.json
- examples/json-extension/package.json
> Release v0.11.3

- .github/workflows/ci.yml
- CHANGELOG.md
- RELEASING.md
- pygls/__init__.py
- setup.cfg
This is my first release. There isn't any documentation on how to release, and I'm having some trouble with the version number. So I'm putting this up for some feedback.
Even though I'm explicitly setting `__version__` to `0.12-rc1`, the build process always automatically decides on this version: `pygls-0.12rc2.dev0+g96bc69d.d20220704`, based on the git tag. I've noted my steps in a new `RELEASING.md` file in the root.
> Release: v0.12-rc1

- CHANGELOG.md
> fix link in changelog

- Implementations.md
Thanks to your library. It's great for python developers.
> Add stata language server to Implementations.md

- CHANGELOG.md
- pygls/__init__.py
~- [] Tests have been included and/or updated, as appropriate~
~- [ ] Docstrings have been included and/or updated, as appropriate~
~- [ ] Standalone docs have been updated accordingly~
~- [ ] [CONTRIBUTORS.md][contributors] was updated, as appropriate~
> release: v0.12.1

- Implementations.md
Hello :wave:
- [we](https://www.github.com/avast) have released a new language server called YLS
- https://www.github.com/avast/yls
- we would like to feature it in this list, with hopes that it will serve the community
- as inspiration/reference/how to use it/...
Thanks for pygls :)
> Add YARA language server to Implementations.md

- CHANGELOG.md
- pygls/__init__.py
- setup.cfg
Fixes #266
~- [] Tests have been included and/or updated, as appropriate~
~- [ ] Docstrings have been included and/or updated, as appropriate~
~- [ ] Standalone docs have been updated accordingly~
~- [ ] [CONTRIBUTORS.md][contributors] was updated, as appropriate~
> fix: Relax Python version <4

- docs/source/conf.py
- docs/source/index.rst
- docs/source/pages/migrating-to-v1.rst
Here's an initial attempt at a migration guide for the 1.0 branch.
- The table of renamed types and constants was manually generated so I may have missed some and there could be errors.
There's a also a few types I couldn't find obvious replacements for (I probably didn't look hard enough) so some help reviewing this table in particular would be appreciated :slightly_smiling_face: 
- Have I missed anything obvious?
> Initial draft of a migration guide

- .github/workflows/ci.yml
- examples/fountain-extension/package-lock.json
- examples/fountain-extension/src/server.py
- examples/fountain-extension/src/server.ts
- pyodide_testrunner/test-runner.js
**This is for the unreleased 1.0 branch**
- Update main CI workflow to test on the released version of Python 3.11
- Update version of Pyodide used in tests to latest release
- Update glue code in example fountain extension to align with changes on the 1.0 branch
> Pyodide Updates

- docs/source/pages/migrating-to-v1.rst
Little fixes for v1 migration page.
> docs: Use proper RST lsit syntax in v1 migration

- README.md
Fixes the code example in the README
> Fix the code example in the README

- CHANGELOG.md
Fix missing links in changelog
> fix missing links in changelog

- pygls/protocol.py
- pygls/server.py
A handful of type-checking fixes.
There's lots more that could be done - try `mypy --strict pygls` if you want to see.  But this covers enough of the public API that typechecking from jedi-language-server is happy.
> some type-checking fixes

- docs/source/pages/getting_started.rst
> Fix wrong argument for CompletionList

- CHANGELOG.md
- setup.cfg
Fixes #270 (again)
- [/] Tests have been included and/or updated, as appropriate
> fix: Relax to Python <4 (again)

- docs/source/pages/migrating-to-v1.rst
Hi!
We just finished the migration to v1.0.0, so I thought it would be useful for others to include it into known migrations docs :) . 
PS: I hope I got the .rst syntax right
- [/] Tests have been included and/or updated, as appropriate
- [/] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])
> docs: Add yara-language-server to known migrations

- docs/source/pages/testing.rst
- docs/source/pages/tutorial.rst
Resolves https://github.com/openlawlibrary/pygls/issues/322
> docs: Correct link to JSON VScode extension

- Implementations.md
I found a pygls implementation for mypy and added it to the documentation.
- vscode-mypy
- <https://github.com/microsoft/vscode-mypy>
> chore: Add Microsoft's vscode-mypy to Implementations.md

- .gitignore
- examples/servers/json_server.py
- pygls/capabilities.py
- tests/lsp/test_diagnostics.py
Implements diagnostic pull feature mentioned in https://github.com/openlawlibrary/pygls/issues/346
> feat: Add document diagnostic capability

- examples/servers/json_server.py
- pygls/capabilities.py
- tests/lsp/test_inline_value.py
Adds support for inline value request.
> feat: adds inline value support

- .github/workflows/ci.yml
Just a quick fix to maybe get us more green ticks. 
> ci: increase Pyodide CI retries to 6

- .github/workflows/release.yml
Hopefully there's not too much back forth fixing these release bugs 😬
> ci: fix changelog update stanza

- pyproject.toml
Quick release to get a fix for #395 public
> build: v1.1.1

- Implementations.md
> Add `pytest-lsp` and `lsp-devtools` to Implementations.md

- poetry.lock
- pyproject.toml
> Update `lsprotocol` to 2023.0.1

- Implementations.md
Added a new extension base on `pygls`. Thanks a lot @alcarney for guiding.
> update implementation.md with Kedro extension

- docs/source/user-guide.rst
> Fix typo in user guide

- RELEASING.md
I'm surprised I hadn't made this already. Maybe I did but it's somewhere else?
Let's maybe do a release before merging this, so as to check that it's accurate.
> docs: add RELEASING.md doc

- pyproject.toml
With all the recent asyncio changes it's probably time for another preview release so that they can be tested in the wild. 
```sh
```
> build: v2.0.0a2

- README.md
> chore: fix migration guide link

- pygls/client.py
Fix some grammar in a comment.
```sh
```
> docs: tweak a comment in client.py

- pygls/lsp/_base_server.py
- scripts/generate_code.py
- tests/test_server_connection.py
> Fixes error when passing max_workers

- pyproject.toml
The main changes being #516 and #527 but there are some smaller fixes as well, see [here](https://github.com/openlawlibrary/pygls/compare/v2.0.0a2...main)
```sh
```
> Release v2.0.0a3

- pyproject.toml
Not a huge batch of changes, a couple of fixes for 2.0a3 and bumping lsprotocol to 2025.0.0rc1
```sh
```
> build: v2.0.0a4
