openlawlibrary/pygls

- pygls/protocol.py
Request data is deserialized to object, so we have to access its fields with dot notation.
> Fix AttributeError in _handle_notification method

- pygls/server.py
- tests/test_language_server.py
We were passing always the `LanguageServerProtocol` class, instead of parameter from the constructor.
> Fix passing custom protocol to language server + tests

- CONTRIBUTORS.md
- pygls/protocol.py
- pygls/types.py
- tests/test_language_server.py
Some LSP clients do not send `workspaceFolders` as a parameter and this line throws an AttributeError on those. Protocol allows for this field to be omitted
> Fix possibly non existing parameter

- CHANGELOG.md
- CONTRIBUTORS.md
- examples/json-extension/server/tests/unit/test_features.py
- pygls/exceptions.py
- pygls/protocol.py
- pygls/workspace.py
- tests/conftest.py
- tests/test_workspace.py
This fixes #50 by allowing a fresh VS Code session with no workspaces open to not halt the language server.
It also fixes the error message by converting the data property into a string (rather than `[object Object]`).
I apologize for my formatting slip up, I pushed to my fork _then_ realized NeoVim auto-formatted the rest of the code... so a bit of commit bloat.
1. Setup VS Code so that the next time it opens, there are no workspaces opened.
2. Enter VS Code in debug mode with the extension loaded.
3. Open a JSON file and start writing.
4. Crashes.
```
workspace_folders = getattr(params, 'workspaceFolders', [])
for folder in workspace_folders:
self.workspace.add_folder(folder)
```
```
[Error - 12:11:01 AM] Server initialization failed.
Message: TypeError: 'NoneType' object is not …
```
> Bugfix open workspace assumption

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
The idea is for contributors to fill-out the description and have the code review checklist as a guide in developing the PR.
The code reviewer is the one who will complete the code review checklist (checking all boxes) before approving.
> Add PR template

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/protocol.py
- tests/test_protocol.py
Sorry, I accidentally send incomplete request...
I will update it to make this request complete.
This request is to handle message fields that is not valid as python class fields (such as `__dummy__`) from the client.
For example, [Eglot](https://github.com/joaotavora/eglot), which is a LSP client for emacs send `initialized` notification with `__dummy__` parameter.
Currently language servers that are based on pygls fail with the following exception message:
```
Process EGLOT (v1/cwl-mode) stderr finished
Traceback (most recent call last):
File "/Users/tanjo/repos/cwl-language-server/cwl_language_server/main.py", line 42, in <module>
server.start_io()
File "/Users/tanjo/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pygls/server.py", line 164, in start_io
self.lsp.data_received))
File …
```
> Fix handling notification/request parameters that is not used for class fields name from the server

- CHANGELOG.md
- pygls/protocol.py
- tests/test_protocol.py
> Remove error or result field when sending JsonRPCResponseMessage

- CHANGELOG.md
- docs/source/index.rst
- docs/source/pages/advanced_usage.rst
- pygls/protocol.py
- pygls/server.py
- pygls/types.py
- pygls/workspace.py
- tests/test_document.py
- tests/test_workspace.py
> Multiple text document sync options

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/types.py
- pygls/workspace.py
FULL syncs were broken for me unless I set the server to only accept FULL syncs. This PR fixes the bug.
Even if a server accepts INCREMENTAL SyncKinds, clients may request a FULL SyncKind. In LSP 3.x, clients make this request by omitting both Range and RangeLength from their request. Consequently, the attributes "range" and "range_length" will be missing from FULL content update client requests in the pygls Python library.
The client library I use is [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim), which only supports full updates at present. It explicitly removes the attributes Range and RangeLength from its request when they are None, as the LSP specification requests. This clearly flows to the lower-level `_apply_incremental_change(` function.
I haven't been …
> Fix full updates

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/protocol.py
- pygls/server.py
- tests/test_protocol.py
This PR fixes the logic for parsing a batch of messages in `data_received()`, where each message body may contain a literal `Content-Length` keyword.
Previously, if a document contained this keyword, then the server would crash, because it attempted to split messages on this keyword.
Now, instead of splitting the messages on the keyword, it parses content length from the first keyword, and then extracts the message based on the length. After that, the parsing loop is repeated, until no more messages can be read.
Update: I added handling of partial messages, since some messages may arrive in chunks.
[contributors]: …
> Fix message parsing for documents containing Content-Length keyword

- pygls/py.typed
- setup.py
See https://www.python.org/dev/peps/pep-0561/ . With such package metadata users of pygls running type checkers will use the type definitions provided by pygls and won't have to manage stubs themselves.
> PEP561: Declare that this package has inline types

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/types.py
- tests/test_types.py
This helps debugging and simplify testing, where we can just assert that ranges or locations are equals.
> types: add __repr__ and __eq__ support to Range and Location

- CHANGELOG.md
- pygls/protocol.py
- pygls/types.py
Using enums allows more precise type checking. The current code in types.py was already using *Kind classes as if they were enums, which mypy reported as type errors:
pygls/types.py:377: error: Incompatible default for argument "severity" (default has type "int", argument has type "DiagnosticSeverity")
pygls/types.py:663: error: Incompatible default for argument "trace" (default has type "str", argument has type "Optional[Trace]")
WatchKind is handled a bit differently, because valid values can be combined with |, like the default value 7.
> types: use enum class for enums

- CHANGELOG.md
- pygls/server.py
Use a TypeVar so that type checkers understand that the signature is
same as the decorated functions, so that these functions can be
typechecked.
fixes #88
> server: more specific types for decorators

- Implementations.md
Adding reference to a language server I wrote for [zc.buildout](http://docs.buildout.org/en/latest/) profiles.
> Add zc.buildout Language Server to Implementations

- setup.py
Before, `pip install .` or `python setup.py install` would install `/usr/lib/python3.x/site-packages/tests`. This restricts setuptools' package discovery to exclude it.
> Don't install the tests to site-packages

- MANIFEST.in
- appveyor.yml
- azure-pipelines.yml
- setup.cfg
- setup.py
- tox.ini
- Run typechecker (mypy) as part of test suite
- Run on multiple python versions
- Run on linux
Fixes #96 
> Run tests and linters on multiple python versions and on linux

- .gitignore
- pygls/types.py
Add `InsertTextFormatEnum` for [CompletionItem](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion).
Also change type annotation and default value of `insert_text_format` to `int = 1`.
> Add InsertTextFormat enum

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/server.py
If ctr+c is pressed while the server is running in a command shell, a `KeyboardInterrupt` exception is raised to stop the asyncio event loop.
This commit catches that exception to exit the server normally without printing a traceback.
> Exit server normally via KeyboardInterrupt exception

- CHANGELOG.md
- pygls/protocol.py
This commit modifies the `JsonRPCProtocol._send_data()` method in order to avoid duplicated utf-8 encoding of body content.
Up to this commit the serialized json payload was encoded to just receive its length and once more together with the whole content header.
The `header` and `body` are created, encoded and streamed independently, now.
> Optimize message serialization

- CHANGELOG.md
- pygls/types.py
- pygls/workspace.py
- tests/conftest.py
- tests/test_document.py
Closes #116.
Python uses utf-32 for strings, but the language-server-protocol uses utf-16 to encode strings. Hence higher level unicode code points are represented by two utf-16 code units. Thus the `position.character` needs to be adjusted in case of the presence of such unicode characters.
see: https://github.com/openlawlibrary/pygls/issues/116, https://github.com/microsoft/language-server-protocol/issues/376
This PR therefore introduces two methods to the `Documents` class to handle conversion between utf-16 and utf-32 column offsets for general use.
The new methods are used in the `offset_at_position()`, `word_at_position()` and `_apply_incremental_change()` methods.
Notes:
1. The conversion needs information about the line's content. Hence it feels natural to add the functionality to …
> Fix utf-16 to utf-32 character offsets.

- CHANGELOG.md
- pygls/types.py
This commit 
- adds `ClientInfo` to `InitializeParams`
- adds `HoverParams`
- derives `TextDocumentItem` from `VersionedTextDocumentIdentifier`
- fixes some typos related with `__init__`.
- fixes #122
> Fix type definitions

- CHANGELOG.md
- pygls/types.py
- pygls/workspace.py
- tests/test_document.py
The rangeLength attribute in the TextDocumentContentChangeEvent is marked deprecated and therefore no longer enforced by pygls. If it is passed by a client, it is accepted silently, but as it is not needed for text synchronization at all, it is marked optional.
As the result the whole Document.apply_change() method can be slightly simplified.
> Mark deprecated rangeLength optional in TextDocumentContentChangeEvent

- CHANGELOG.md
- pygls/feature_manager.py
Turn coroutine to async def to resolve deprecation warning:
`"@coroutine" decorator is deprecated since Python 3.8, use "async def" instead`.
> Turn coroutine to async def

- pygls/capabilities.py
- pygls/lsp/types/general_messages.py
- setup.py
Related to #139 (and this pull request is against that branch).
I have:
- allowed pydantic and typeguard versions to go higher.  typeguard declares that it follows semantic versioning, so 2.x should be safe.  pydantic seems to make breaking changes at minor releases; however 1.8 works just fine so I've allowed 1.7.x and 1.8.x
- tweaked `ClientCapabilities.has_capability()` along the lines I suggested in https://github.com/openlawlibrary/pygls/pull/139#issuecomment-798347921 ie added a type annotation, and allowed it to return a default value.  I've also renamed it to `get_capability()`, since it handles not only boolean values (eg `text_document.completion.completion_item.documentation_format` is a list of `MarkupKind`).
> Lsp miscellany

- CHANGELOG.md
- pygls/protocol.py
- pygls/server.py
- pygls/utils.py
- setup.py
Closes #118 and #130.
Ensures that `pygls` process will terminate if the client process is not alive.
> Periodically check client pid and exit server

- CHANGELOG.md
- pygls/lsp/types/workspace.py
Closes #155.
More info is in the issue comments.
> Fix change_notifications type (pydantic bug)

- CHANGELOG.md
- pygls/lsp/types/basic_structures.py
- tests/lsp/test_rename.py
Closes #159.
The reason I couldn't do this:
```python
class JsonRPCRequestMessage(JsonRpcMessage):
"""A class that represents json rpc request message."""
id: Union[int,str]
method: str
params: Any
```
is that in the case of `Union`, `pydantic` tries to convert the input to the first valid type, so, if you pass `id='1'`, an object will have a field of type `int` `id=1`...
> Fix pydantic Unions type conversion

- CHANGELOG.md
- pygls/capabilities.py
Avoid setting fields in server capabilities to `None`, because explicitly setting them causes pydantic to serialize them, which is not what is wanted.
See https://github.com/pappasam/jedi-language-server/issues/108
> Avoid unwanted "null"s in server capabilities

- pygls/workspace.py
Only the `uri` and `version` attributes of `text_doc` are used. Therefore `text_doc` can be a `VersionedTextDocumentIdentifier` and does not have to be a `TextDocumentItem`.
> Relax text_doc type to VersionedTextDocumentIdentifier

- pygls/lsp/types/basic_structures.py
- tests/lsp/test_rename.py
Closes #176 . Missing kind causes error in VS Code when renaming packages.
> Adding kind field to resource file operation types

- CHANGELOG.md
- pygls/server.py
- tests/test_server_connection.py
Fixes #173.
I agree with recent comments saying that receiving an empty header at readline tells you that you're done: per <https://docs.python.org/3/tutorial/inputoutput.html#methods-of-file-objects>
> If the end of the file has been reached, f.read() will return an empty string ('') ...
> ... if f.readline() returns an empty string, the end of the file has been reached ...
So that's what this does.
If this looks good, I wonder whether it's time for a 0.10.3 release?  There have been a handful of bug fixes that it would be nice to see published.
> exit when no more data available

- pygls/protocol.py
This fixes #187.
By raising the exception stored in the future and then handling it `sys.exc_info()` is able to see the exception and provide the details which can then be logged. With this change I now see a detailed traceback in the log.
```python
ERROR:pygls.protocol:Exception occurred in notification: "{'code': -32602, 'message': 'ZeroDivisionError: division by zero', 'data': '{\'traceback\': [\'  File "/home/alex/Code/pygls/pygls/protocol.py", line 246, in _execute_notification_callback\\n    raise future.exception()\\n\', \'  File "/home/alex/Code/pygls/pygls/feature_manager.py", line 68, in wrapped\\n    return await f(server, *args, **kwargs)\\n\', \'  File "/home/alex/Code/pygls/examples/json-extension/server/server.py", line 149, in did_open\\n    x = 1 / 0\\n\']}'}"
Traceback …
```
> Fix missing tracebacks in async notification handlers

- CHANGELOG.md
- CONTRIBUTORS.md
- docs/source/pages/advanced_usage.rst
- examples/json-extension/.vscode/launch.json
- examples/json-extension/server/__main__.py
- pygls/protocol.py
- pygls/server.py
- setup.cfg
- tox.ini
Implementation of [WebSocket](https://tools.ietf.org/html/rfc6455) server. This PR allows users to start the WebSocket server on a given `host` and `port` that will "wrap" the LSP protocol. The interface is the same as other `SERVER.start_*` methods.
The main use case is to create convenient interface to interact with editors that are embedded in internet browsers (for example [Monaco LSP-client](https://github.com/TypeFox/monaco-languageclient)), this could potentially allow for broader adoption.
Related to #85 
> Add WebSocket server

- CHANGELOG.md
- CONTRIBUTORS.md
- README.md
- docs/source/pages/advanced_usage.rst
- docs/source/pages/getting_started.rst
- tests/test_server_connection.py
This replaces all references to `localhost` with `127.0.0.1`.
I've verified this locally this as a patch to the conda-forge feedstock, which builds under Docker: I'm not a huge Docker fan, but it is _a thing_, and it seemed like updating the docs along with the tests might save someone some trouble in the future.
- fixes #165
> replace references to localhost with 127.0.0.1 for docker and friends

- examples/json-extension/.gitignore
The instructions on the `README` tell the user to create an environment called `env`. I guess we should match the `.gitignore`.
> Add env to .gitignore

- CONTRIBUTORS.md
- pygls/protocol.py
- tests/lsp/test_progress.py
- tests/lsp/test_references.py
This addresses #217 and #231.
I am still new to the project, so I may not have the full story. But it
started with a somewhat far-reaching merge to remove defaults from all
serialisable fields in the API: #198. This had the knock-on effect of
regressing progress notifications, as reported by @MatejKastak in #217.
One of their suggestions is to not use `exclude_unset=True`. Some months
later @dimbleby suggested that `exclude_none=True` would also fix the
issue[1]. Considering those 2 suggestions, let's replace
`exclude_unset=True` with `exclude_none=True`.
1. https://github.com/openlawlibrary/pygls/pull/198#issuecomment-1086864429
[contributors]: …
> API: drop None rather than unset in JSON response

- CONTRIBUTORS.md
- docs/source/pages/getting_started.rst
- pygls/feature_manager.py
- pygls/server.py
First of all thanks, I've found this package really useful.  This small PR just fixes a few bits of (I think) outdated documentation in `getting_started` and in a few docstrings.
Possibly related is https://github.com/openlawlibrary/pygls/pull/94, though I'm a bit confused by that PR since the diff appears to be the opposite of what the PR title says?
Thanks :slightly_smiling_face:  
> Fix Outdated Documentation and Docstrings

- CHANGELOG.md
- pygls/workspace.py
- tests/test_document.py
Hi!  I found myself re-writing slight variations of `Document.word_at_position` for "words" which aren't alphanumeric, but allowing regular expressions to be passed to the method in question means I can re-use it.  So this PR just adds a couple of parameters to `Document.word_at_position`.
Hopefully the exact behaviour should be clear from the docstrings.
The new parameters have default values set to the previous hard-coded patterns so I think this should be fully backward compatible with the same behaviour.
Thanks! :slightly_smiling_face: 
> Generalise word_at_position for Documents

- pygls/lsp/types/basic_structures.py
- pygls/protocol.py
- tests/test_protocol.py
This undoes the change in #236 as well as bring back the explicit setting of non `None` default fields as suggested in [this comment](https://github.com/openlawlibrary/pygls/issues/245#issuecomment-1173166210)
This commit also introduces serialization test cases that hopefully cover all the scenarios raised in #245, #231 and #198
Let me know if you think there are any other scenarios that should be covered by the new tests.
Closes #245
> Change `exclude_none` back to `exclude_unset`

- CHANGELOG.md
- pygls/workspace.py
- tests/test_language_server.py
This ensures that `pygls` remembers the `language_id` of text documents opened by the client.
Closes #212 
> Keep track of a text document's `language_id`

- pyodide_testrunner/run.py
If something is wrong with the test running on CI and selenium get a timeout,
the test output was not displayed.
- [/] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])
> pyodide_testrunner: display console on error

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/__init__.py
- setup.cfg
Currently the restriction on pydantic does not allow us select a single version that works for python 3.7-3.11. This PR removes the upper bound on python version <3.11. This allows pygls to select a single version of pydantic that works on all python versions.
> Remove upper bound on pydantic for python <3.11

- CHANGELOG.md
- docs/source/pages/advanced_usage.rst
- pygls/exceptions.py
- pygls/protocol.py
- pygls/server.py
- tests/ls_setup.py
- tests/lsp/test_errors.py
This includes a notable, perhaps even controversial, behaviour change:
All errors other than LSP requests are now sent to the client as `showMessage.type = MessageType.Error` messages. This may result in existing custom LSP servers showing errors that were not seen before, these aren't new errors, just previously undisplayed errors.
Another advantage to this is that it is now easier to test error handling. When running end to end tests, all errors are now accessible in the client.
Also, `JsonRPCProtocol.data_receieved()` now catches unhandled errors.
Fixes #277.
> fix: Improved error handling

- CHANGELOG.md
- pygls/server.py
- tests/test_server_connection.py
This is an attempt at fixing #268
First this commit introduces a test that runs a websocket server in a separate thread.
**Note:** While the test appears to work as intended, due to running the server in a separate thread I'm unable to reproduce the exact error I see in the original issue. I instead get a different error about there not being an event loop.
```
$ pytest tests/test_server_connection.py::test_ws_server
=============================================== test session starts ================================================
platform linux -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /var/home/alex/Projects/pygls, configfile: pyproject.toml
plugins: typeguard-2.13.3, timeout-2.1.0, cov-3.0.0, asyncio-0.19.0, lsp-0.1.2
asyncio: mode=auto
collected 1 item …
```
> Fix websocket based servers

- CHANGELOG.md
- pygls/__init__.py
A minor version bump here, because there are 2 behaviour changes, namely more error messages being sent to the client, and a warning log line if `LanguageServer("my-server-name", "0.0.1")` is instantiated without the server name and version.
Added:
- Add `name` and `version` arguments to the constructor of `LanguageServer` ([#274]) [#274]: https://github.com/openlawlibrary/pygls/issues/274 Changed:
- Default behaviour change: uncaught errors are now sent as `showMessage` errors to client. Overrideable in `LanguageServer.report_server_error()`: https://github.com/openlawlibrary/pygls/pull/282 Fixed:
- `_data_recevied()` JSONRPC message parsing errors now caught
- Fix "Task attached to a different loop" error in `Server.start_ws` ([#268])
> Release v0.13.0

- pygls/protocol.py
- pygls/server.py
- pygls/workspace.py
- tests/lsp/test_code_action.py
- tests/test_protocol.py
- The `mypy` issues identified by @dimbleby should now be resolved
- By replacing the `attrs.field()` definitions in the `JsonRPCXXX` type definitions with structure hooks, custom messages should no longer be corrupted, while still retaining the existing `dict_to_object` behavior. Closes #285 
- The module level `converter` in `pygls/protocol.py` has been replaced with one attached to the `JsonRPCProtocol` object's instance which can now be overriden by passing a  custom `converter_factory` to the `Server` object's constructor. Closes #286 
- [/] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])
[changelog]: …
> Fixes for the v1.0 branch

- pygls/capabilities.py
- pygls/lsp/__init__.py
- tests/test_capabilities.py
This fixes the construction of the `workspace.fileOperations` fields of the server's capabilities by passing through the `FileOperationRegistrationOptions` provided when registering features like `WORKSPACE_DID_DELETE_FILES`
This also resolves [the issue](https://github.com/openlawlibrary/pygls/pull/273#issuecomment-1301546322) I was having with the runtime type checking of the given options 
Closes #278 
> Fix construction of `workspace.fileOperations` server capabilities

- CHANGELOG.md
- README.md
- docs/source/pages/getting_started.rst
- pygls/__init__.py
- pygls/lsp/types/language_features/code_action.py
Add doc/README updates to recommend the v1 alpha release for new projects.
This came up in #293 where a missing feature was identified in the current release, but is fixed in the v1 alpha release. Whereas we're only _probably_ ready to release v1, we're _definitely_ ready to recommend it for new projects. 
Missing feature notes:
Strictly, Pygls only currently supports LSP v3.15, but this feature was added in 3.17. Ideally we wouldn't mix and match features from different versions. Ideally we should wholesale support a version. Anyway, we're soon to release a breaking change version of Pygls that follows Microsofts own Python LSP types #273.
Fixes #293
[changelog]: …
> Recomend v1 alpha release for new projects

- docs/source/pages/migrating-to-v1.rst
- pygls/protocol.py
- pygls/server.py
- tests/test_server_connection.py
I think in #274  we said we wanted to make the `name` and `version` arguments to a `LanguageServer` object mandatory?
This PR removes the warning and default arguments meaning they now have to be provided by the language server author.
> Make `name` and `version` arguments mandatory

- examples/json-extension/README.md
when it comes to setting correct Python path for lanuching a vsc, it should be python.interpreterPath instead of python.pythonPath
> change pythonPath settings for VSC

- CHANGELOG.md
- examples/json-extension/server/server.py
The spec [1] and pygls implementation [2] need the token to be unique.
By using an hardcoded token like this, the progress works only one time,
the second time there's an error that token is already registered.
[1]: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#serverInitiatedProgress
[2]: https://github.com/openlawlibrary/pygls//blob/ee17487e4f40f971e7ec6f7711fa8334c5b7b127/pygls/progress.py#L28
> json-extension: use an unique token for progress example

- CHANGELOG.md
- docs/source/pages/advanced_usage.rst
- examples/json-extension/server/server.py
- examples/json-extension/server/tests/unit/test_features.py
- pygls/protocol.py
- pygls/server.py
It turns out the `workspace/configuration` request requires a `WorkspaceConfigurationParams` object, rather than a plain `ConfigurationParams` object. 
This PR
- Fixes the `AttributeErrors` seen in the various `get_configuration_xxx` commands in the example json extension, as well as adding test cases to cover them going forward. 
- Fixes the type annotations in the various `get_configuration_xxx` methods in the pygls codebase
- Updates the documentation to match
Fixes #307 
[commit messages]: …
> Fix 'ConfigurationParams' object has no attribute 'partial_result_token errors

- CHANGELOG.md
- pygls/protocol.py
- pygls/server.py
- tests/lsp/test_diagnostics.py
Fixes #211
Includes deprecation warning for old method signature
I don't know if I'm being too clever here?
Also, does anybody know why there are often 2 public methods to do the same thing like this? Therefore, we can call both `pygls.server.LanguageServer.publish_diagnostics` and `pygls.protocol.LanguageServerProtocol.publish_diagnostics`. I assume it's because `pygls.server.LanguageServer` is the more friendly user-facing class, whilst `pygls.protocol.LanguageServerProtocol` is internal and has to be comprehensive.
> fix: True LSP Diagnostic param, with `version`

- CHANGELOG.md
- setup.cfg
I've been playing around with using `pyright` as a language server recently and have been bitten by the issue described in #232. Removing the `data_files` definition from `setup.cfg` seems to fix the issue.
As far as I can tell it doesn't break the packaging either as the `py.typed`  and `ThirdPatyNotices.txt` files are still included thanks to the declarations in `MANIFEST.in`
Closes #232 
> Remove incorrect data files definition

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/lsp/__init__.py
- setup.cfg
- tests/test_feature_manager.py
Fixes incompatible function call and the expected test failure message.
> Update typeguard to 3.x

- CONTRIBUTORS.md
- examples/json-vscode-extension/server/tests/unit/test_features.py
- setup.cfg
Part of the tests already use unittest.mock so switch the last mock module user over and drop the mock test dependency.
Drop mock dependency 
- [/] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])
> Drop mock dependency

- CHANGELOG.md
- pygls/server.py
Before this commit `pygls` would override the event loop for the current thread even when given an existing loop to use.
Now `pygls` will rely on `asyncio.new_event_loop` to create the appropriate event loop for the platform and only call it when `loop=None`
This commit also introduces the `_own_loop` flag which is used to make sure `pygls` does not close an event loop it does not own.
Related: #334 
- [/] Tests have been included and/or updated, as appropriate …
> Ensure that `pygls.Server` uses the event loop it is given

- CHANGELOG.md
- CONTRIBUTORS.md
- pygls/feature_manager.py
- tests/test_feature_manager.py
The following example fails on `main` because the annotation is a string rather than a concrete type due to the use of `from __future__ import annotations`. `typing.get_type_hints` can be used to resolve the annotations for the signature to support detection in this case. 
```python
from __future__ import annotations
from pygls import server
async def example(
foo: server.LanguageServer,
params: None,
) -> None:
pass
from pygls.feature_manager import has_ls_param_or_annotation
assert has_ls_param_or_annotation(example, server.LanguageServer)
```
This can also be reproduced by wrapping the annotation type in a string manually (as I do in the test in this pull request).
- ~[ ] Docstrings have been included and/or updated, as appropriate~
- ~[ ] Standalone docs have been updated accordingly~ …
> Fix detection of `LanguageServer` type annotation when future annotations are used

- CHANGELOG.md
- pygls/workspace.py
- tests/test_document.py
> fix: Correctly cast from UTF16 positions

- pyproject.toml
Github Actions for windows uses Python 3.7.9 not 3.7.16. This wasn't picked up in the PR that introduced the original lock because of dependency caching. See:
https://github.com/openlawlibrary/pygls/actions/runs/5702563535/job/15454396739#step:6:12
> build(deps): lock min Python version to 3.7.9

- .github/workflows/ci.yml
This is to get around a curious issue that isn't resolved by dependency locking. The flakey error is:
`ImportError: cannot import name 'Any' from 'typing_extensions'`
> ci: retry Pyodide tests

- .github/workflows/ci.yml
It won't be long now before Python 3.12 becomes available (see [schedule](https://peps.python.org/pep-0693/#schedule))
By making use of the [`allow-prereleases`](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases) flag to `actions/setup-python`, we should be able to start testing on the pre-release version of Python now and have the pipeline automatically upgrade to the real thing when it becomes available
> ci: Test against Python 3.12

- .github/workflows/ci.yml
- commitlintrc.yaml
- docs/source/conf.py
- docs/source/index.rst
- docs/source/pages/reference.rst
- docs/source/pages/reference/clients.rst
- docs/source/pages/reference/types.rst
- poetry.lock
- pygls/client.py
- pygls/lsp/client.py
- pyproject.toml
- scripts/generate_client.py
- tests/client.py
- tests/pyodide_testrunner/run.py
- tests/test_client.py
This renames the new client objects to something that better reflects their purpose.
- In `pygls/client.py`, `Client` is now called `JsonRPCClient`
- The auto generated `LanguageClient` in `pygls/lsp/client.py` is now called `BaseLanguageClient`
This PR also performs some other house keeping tasks
- Bump `lsprotocol` to `2023.0.0a3` which should include all the fixes required for #356 
- The auto generated client now references LSP types via the `types` module rather than importing them directly which cuts out the 100s of lines of imports at the top of the file
- Update the documentation to include reference API documentation for the `JsonRPCClient` and `BaseLanguageClient`
> Rename client objects

- .readthedocs.yaml
- docs/requirements.txt
Unsurprisingly, #359 broke the [docs build](https://readthedocs.org/projects/pygls/builds/21780848/) - especially when you consider it was still running on Python 2.7!
This PR adds a `.readthedocs.yaml` file, which is now the [recommended way](https://blog.readthedocs.com/migrate-configuration-v2/) to configure builds on the platform.
The `docs/requirements.txt` file was generated using a `poetry export --with docs` command, so we'll have to remember to periodically update it - unless we find a way to automate its generation.
> chore: add .readthedocs.yaml

- examples/servers/json_server.py
- examples/vscode-playground/package.json
- examples/vscode-playground/src/extension.ts
This brings back the ability to execute commands provided by the language server in the `vscode-playground` extension.
Instead of encoding all the commands in the `package.json` file, the extension inspects the `ServerCapabilities` of the `initialize` response to determine which commands a server provides. It then presents a quick pick list of commands the user can choose to run.
This should mean commands (that don't take any arguments at least) now "just work" with the playground extension
This PR also re-defines the example configuration keys in the `packae.json` for  `json_server.py` otherwise VSCode simply responds with `null` when the configuration values are requested
Closes #365 
> fix: ensure server commands can be executed

- pygls/capabilities.py
Add support for workspace symbol resolve request.
> feat: add workspace symbol resolve

- examples/servers/json_server.py
- pygls/capabilities.py
- tests/lsp/test_diagnostics.py
Adds workspace diagnostic request support.
> feat: add workspace diagnostic support

- pygls/capabilities.py
- tests/lsp/test_type_hierarchy.py
Adds type hierarchy request support
> feat: adds type hierarchy request support

- docs/source/pages/advanced_usage.rst
- pygls/protocol.py
- pygls/server.py
Before:
```python
def edit_callback(future):
result = future.result()
ls.apply_edit(workspace_edit).add_done_callback(edit_callback)
```
After:
```python
result = await ls.apply_edit_async(workspace_edit)
```
> Add `await` syntax support for sending edit request to client

- .github/workflows/ci.yml
Having problems in CI, looks like a bug got cached, hopefully just busting the cache fixes it.
> chore(ci): bust cache

- examples/servers/code_actions.py
In examples/code_actions, tighten the ADDITION regex so that the 'Evaluate' code action only appears if there's no sum. Previously, after using the action, the lightbulb remained visible in VSCode and would keep appending the sum to the line, resulting in things like `1 + 1 = 2! 2! 2!`
> fix: only show code action when there's no sum

- pygls/workspace/__init__.py
- pygls/workspace/position_codec.py
- pygls/workspace/text_document.py
- pygls/workspace/workspace.py
- tests/test_document.py
Implement the refactoring discussed in #382
- Rename pygls `Position` type to `PositionCodec`
- Create a single `PositionCodec` instance in `Workspace` that is used by all `TextDocument` instances
- Add `position_encoding` and `position_codec` read-only properties to `Workspace`
- Make `position_codec` a read-only property of `TextDocument`
- Improve deprecation warning messages associated with the old position mapping functions that have been replaced by `PositionCodec`
Resolves #382
> refactor: rename server Position to PositionCodec, instantiate it in Workspace

- tests/test_language_server.py
Fixes the following two DeprecationWarnings:
```
tests/test_language_server.py::test_bf_text_document_did_open
C:\_\pygls\tests\test_language_server.py:85: DeprecationWarning: 'workspace.documents' has been deprecated, use 'workspace.text_documents' instead
assert len(server.lsp.workspace.documents) == 1
tests/test_language_server.py::test_bf_text_document_did_open
C:\_\pygls\tests\test_language_server.py:87: DeprecationWarning: 'workspace.get_document' has been deprecated, use 'workspace.get_text_document' instead
document = server.workspace.get_document(__file__)
```
> chore: fix use of deprecated methods in tests/test_language_server.py

- pyproject.toml
Fixes #346 (LSP 3.17 support)
Is this all we need now for a release, to just bump the version number and all the automation takes care of the rest!? Only one way to find out 🤓
> Release v1.1.0: LSP 3.17 support

- pygls/workspace/__init__.py
so that mypy will give jedi-language-server a clean bill of health, else:
```
jedi_language_server/text_edit_utils.py:26: error: Module "pygls.workspace" does not explicitly export attribute "Workspace"  [attr-defined]
```
> explicit exports from pygls.workspace

- pygls/workspace/workspace.py
- tests/test_workspace.py
> fix: prevent AttributeError root_path when no workspace

- .github/workflows/release.yml
- cliff.toml
Tested at:
https://github.com/tombh/pygls/actions/runs/6386050011/job/17332041127
Let's not merge this until a deploy key has been added as described at:
https://stackoverflow.com/a/76135647 /cc @dgreisen 
> ci: fix release process

- pygls/workspace/position_codec.py
Fixes an incorrect doc comment that was a hangover from the old utf-16 only Position implementation.
> docs: correct doc comment for PositionCodec.client_num_units

- poetry.lock
- pyproject.toml
Bumps upper bound for typeguard from 4.0 to 5.0 allowing installation of typeguard 4.x
Bumps the locked version to `4.1.2`
Tested locally with typeguard `4.1.5`
Allows installation with typeguard 3.x still
Typeguard 4.0 was [released](https://github.com/agronholm/typeguard/releases/tag/4.0.0) back in May and this bound is blocking dependency resolution in other projects e.g. https://github.com/astral-sh/ruff-lsp/issues/299
> build: allow installation with typeguard 4.x 

- pyproject.toml
This release will include the following PRs:
* chore: split protocol.py into own folder/files by @tombh in https://github.com/openlawlibrary/pygls/pull/398
* docs: correct doc comment for PositionCodec.client_num_units by @RossBencina in https://github.com/openlawlibrary/pygls/pull/399
* build(deps-dev): bump urllib3 from 2.0.6 to 2.0.7 by @dependabot in https://github.com/openlawlibrary/pygls/pull/401
* build: allow installation with typeguard 4.x  by @zanieb in https://github.com/openlawlibrary/pygls/pull/405
> build: v1.1.2

- pyproject.toml
* Remove dependency on `typeguard` by @karthiknadig in https://github.com/openlawlibrary/pygls/pull/411
* Simplify vscode-playground setup and fix Python discovery by @alcarney in https://github.com/openlawlibrary/pygls/pull/374
* chore: pin lsprotocol to 2023.0.0 by @alcarney in https://github.com/openlawlibrary/pygls/pull/414
> build: v1.2.0

- pygls/exceptions.py
- pygls/protocol/json_rpc.py
The error on a `ResponseErrorMessage` is supposed to be a `ResponseError`, not a dictionary.
Older versions of cattrs seem to have tolerated the mistake, but newer ones don't.  
The reason that this repository's own tests don't find this is that it continues to support python 3.7: and the versions of cattrs that don't like the mistake have dropped support for python 3.7.  So `poetry update` here does not get the bug-exposing update.
However users who are on recent python versions do get the update, and do experience errors eg see https://github.com/pappasam/jedi-language-server/issues/296
A couple of meta-comments on this issue:
- probably it's time to drop support for python 3.7 here: much of the world has already done so, and by continuing to support it pygls is not seeing updates that …
> handle ResponseErrors correctly

- examples/servers/.vscode/launch.json
- examples/servers/.vscode/settings.json
- examples/vscode-playground/README.md
- examples/vscode-playground/package.json
- examples/vscode-playground/src/extension.ts
This adds back the ability for language servers to be debugged through the example VSCode extension.
Rather than make the user launch the client and server separately and using a TCP connection, the extension now uses the official Python extension to wrap the server in a debug adapter and automatically starts the debug session.
To debug the server set the `pygls.server.debug` option to `true`.
This will go towards #424 (though the docs will still need to be updated)
> Add support for debugging servers in the VSCode Playground

- pyproject.toml
The main change I think is bumping `lsprotocol` to [2023.0.1](https://github.com/microsoft/lsprotocol/releases/tag/2023.0.1)
All changes:
* ci: don't let Pyodide test fail the whole build by @tombh in https://github.com/openlawlibrary/pygls/pull/420
* feat: drop Python 3.7 support by @tombh in https://github.com/openlawlibrary/pygls/pull/417
* Do the tests really freeze? by @dimbleby in https://github.com/openlawlibrary/pygls/pull/422
* Add `pytest-lsp` and `lsp-devtools` to Implementations.md by @alcarney in https://github.com/openlawlibrary/pygls/pull/426
* Add support for debugging servers in the VSCode Playground by @alcarney in https://github.com/openlawlibrary/pygls/pull/425
* Update `lsprotocol` to 2023.0.1 by @karthiknadig in https://github.com/openlawlibrary/pygls/pull/432
> Release v1.3.0

- pyproject.toml
Poetry requires an EXACT match for the License name in order to auto-populate classifiers. Changed `Apache 2.0` to `Apache-2.0`
From version 1.1.0 forward, after switching to Poetry, PyPI has displayed the license as:
`License: Other/Proprietary License (Apache 2.0)`
PyPI **should** say: 
`License: Apache Software License (Apache 2.0)`
This is caused by the License not being an exact match to what Poetry is expecting.
This is a problem because within enterprise environments, packages are often scanned for security and legal risks. A proprietary, i.e., non-open license can be a legal issue, so it's important to have a proper license declaration to allow automated tools to make a proper evaluation.
Poetry code reference:
https://github.com/python-poetry/poetry-core/blob/219c52e6cb8b086c78f25 …
> Typo: Apache License missing dash: Affects PyPI License Declaration

- pyproject.toml
* Typo: Apache License missing dash: Affects PyPI License Declaration by @WilliamRoyNelson in https://github.com/openlawlibrary/pygls/pull/435
* Add systemd-language-server to implementations by @psacawa in https://github.com/openlawlibrary/pygls/pull/436
* Update Implementations.md with Chapel's language server by @DanilaFe in https://github.com/openlawlibrary/pygls/pull/439
> build: v1.3.1

- pygls/capabilities.py
- tests/test_feature_manager.py
Related to #445 
This change would make `pygls` accept the client's preferred encoding rather than preferring `UTF-16` blindly. For editors that prefer `UTF-32` this is advantageous for `pygls` since the position encoding/decoding becomes simpler.
> Respect client's preferred encoding when possible

- examples/servers/hover.py
Following the best practice guide from "passing language server instance as parameter"
https://pygls.readthedocs.io/en/latest/pages/user-guide.html#passing-language-server-instance
> Update hover.py to use language server argument

- PULL_REQUEST_TEMPLATE.md
I manually added the new lines into this very PR template in this comment...
```sh
```
> docs: add linter commander to PR template

- docs/source/examples/goto.rst
- examples/servers/README.md
I notice the docs is still undergoing lots of change, and it's looking great! This is just a minor change to make this example for discoverable.
```sh
```
> docs: update GotoX title

- pygls/server.py
> docs: fix typo in `server.py`

- pygls/feature_manager.py
See https://github.com/microsoft/vscode-pylint/issues/510 where this
exception arises.
```sh
```
> Provide more detail in exception

- docs/source/user-guide.rst
- examples/servers/json_server.py
- examples/servers/rename.py
- poetry.lock
- pygls/capabilities.py
- pygls/lsp/client.py
- pygls/protocol/language_server.py
- pygls/server.py
- pygls/workspace/text_document.py
- pygls/workspace/workspace.py
- pyproject.toml
- tests/e2e/test_formatting.py
- tests/e2e/test_publish_diagnostics.py
- tests/e2e/test_pull_diagnostics.py
- tests/e2e/test_rename.py
- tests/test_document.py
- tests/test_feature_manager.py
- tests/test_protocol.py
- tests/test_workspace.py
This PR updates `pygls` to latest LSP 3.18 spec and its implementation `lsprotocol` 2024.0.0a2:
- [breaking-change] Names are stabilized with consistent naming for all objects in the spec.
- [proposed] Includes all the proposed APIs that are part of the LSP spec.
- [bug] Includes bug fixes from any bugs or issues reported on lsprotocol 2023.*.  
```sh
```
> Update to latest `lsprotocol` v2024.0.0a2

- .github/workflows/ci.yml
- poetry.lock
- pyproject.toml
Python 3.13 will be [coming soon](https://dev.to/hugovk/help-test-python-313-14j1).
Opening this PR to see what, if any impact 3.13 has on pygls.
We might also want to consider the [free threaded version](https://dev.to/hugovk/help-us-test-free-threaded-python-without-the-gil-1hgf) at some point?
```sh
```
> ci: start testing against Python 3.13

- .github/workflows/ci.yml
Fixes CI issue seen in https://github.com/openlawlibrary/pygls/pull/489#issuecomment-2299694146
```sh
```
> ci: use Python version in cache key

- docs/source/howto/migrate-to-v2.rst
- docs/source/reference/servers.rst
- examples/servers/code_actions.py
- pygls/workspace/__init__.py
- pygls/workspace/workspace.py
This PR removes the code we've previously deprecated (the old workspace and position encoding methods). All removed methods have an alternative which has been documented in the draft migration guide.
I have also started migrating some of my projects and have added them to the list of known migrations.
```sh
```
> chore: remove deprecated code

- RELEASING.md
> chore: properly indent RELEASING.md

- docs/source/howto/migrate-to-v2.rst
- docs/source/reference/uris.rst
- pygls/uris.py
- pygls/workspace/text_document.py
- pygls/workspace/workspace.py
As discussed in #209 this tweaks the `to_fs_path` function to return ``None`` when passed a URI that does not have a `file:` scheme.
This does have a few knock-on effects, but if anything it's going to highlight places where `pygls` makes some incorrect assumptions
Closes #209
```sh
```
> fix: return ``None`` for non ``file:`` URIs

- docs/source/examples/json-server.rst
- examples/servers/code_actions.py
- examples/servers/code_lens.py
- examples/servers/colors.py
- examples/servers/formatting.py
- examples/servers/goto.py
- examples/servers/hover.py
- examples/servers/inlay_hints.py
- examples/servers/json_server.py
- examples/servers/links.py
- examples/servers/publish_diagnostics.py
- examples/servers/pull_diagnostics.py
- examples/servers/rename.py
- examples/servers/semantic_tokens.py
- examples/servers/symbols.py
- examples/servers/threaded_handlers.py
- poetry.lock
- pygls/cli.py
- pygls/client.py
- pygls/protocol/json_rpc.py
- pygls/server.py
- pyproject.toml
- tests/conftest.py
- tests/e2e/test_threaded_handlers.py
- tests/servers/large_response.py
- tests/test_client.py
- tests/test_protocol.py
This PR adds a `start_tcp` method to pygls' `LanguageClient`. This method uses the high-level asyncio APIs I would like to transition the server side over to using (as mentioned in #334).
However, before touching the server-side code I thought it would be best to add tests around the current implementation. So this PR also extends pygls' test suite to add a `--lsp-transport` command line argument.
- `--lsp-transport stdio` (the default), runs the end-to-end tests over stdin/stdout.
- `--lsp-transport tcp`, runs the end-to-end tests over a TCP connection
The `poe test` task used in CI has been updated to run both style of end-to-end tests.
Finaly, this PR also includes some smaller client related fixes
- When the server process exits (in stdio mode), any pending requests are automatically …
> Add TCP support to pygls' LanguageClient

- .vscode/settings.json
- poetry.lock
- pygls/lsp/_base_client.py
- pyproject.toml
Updating lsprotocol to the latest version. Includes proposed LLM features. 
```sh
```
> chore: update to lsprotocol-2024.0.0b1

- pygls/client.py
- pygls/io_.py
- pygls/server.py
- tests/servers/invalid_json.py
Now that we have end-to-end tests around all 3 supported transports (stdio, tcp, websockets). This PR starts the process of migrating the `JsonRPCServer` side of pygls over to the high-level asyncio APIs.
A new `pygls.io_` module has been introduced to hold the I/O code that's common between the client and server sides of pygls, including
- `run` and `run_async` functions, which host the main sync/async message processing loop 
- (Eventually) all reader/writer adapters. Currently there is just `StdinAsyncReader` which allows a server to read from stdin asynchronously
- `Reader` and `AsyncReader` typing protocols which capture the expected shape of the message source.
The client's `start_io` and `start_tcp` as well as the server's `start_io` methods have also been migrated to use the new …
> Move `JsonRPCServer.start_io` to high-level asyncio API 

- docs/source/howto/migrate-to-v2.rst
- pygls/client.py
- pygls/io_.py
- pygls/protocol/json_rpc.py
- pygls/protocol/language_server.py
- pygls/server.py
- tests/conftest.py
- tests/ls_setup.py
- tests/test_server_connection.py
This PR completes the migration of the server-side of pygls to the higher level asyncio APIs
Closes #334 
**start_tcp**
- Since `asyncio.start_server` gives us a reader, writer pair it's enough to reuse the `run_async` method from the `pygls.io_` module.
**start_ws**
- This moves the `WebSocketTransportAdapter` into `pygls.io_` and a new `run_websocket` function, allowing the websocket main loop to be shared between client and server code
- This PR also takes the opportunity to migrate to the new `websockets.asyncio` API
It's also worth noting that the test suite now includes the values of `--lsp-runtime` and `--lsp-transport` in the header pytest prints at the start of a test run
```
$ pytest
=========================================== test session starts …
```
> Migrate `JsonRPCServer.start_tcp` and `JsonRPCServer.start_ws` to high level asyncio APIs

- pygls/exceptions.py
Some LSP server implementations, do not reliably implement error handling. For instance, `gopls` may throw errors without a code when receiving malformed `textDocument/references` requests that contain invalid position data.
This behavior can cause a blocking loop in the message queue, which the user of the `pygls` library cannot catch because it occurs outside their event loop.
This patch introduces a fallback default error code in the jrpc client, ensuring that such errors propagate correctly to the user's event loop. As a result, `pygls` users can catch and handle these errors properly.
```sh
```
> fix: fallback JsonRpcException code for malformed server errors

- pygls/feature_manager.py
- pyproject.toml
- tests/e2e/test_code_lens.py
- tests/e2e/test_colors.py
- tests/e2e/test_formatting.py
- tests/e2e/test_hover.py
- tests/e2e/test_links.py
- tests/e2e/test_semantic_tokens.py
- tests/e2e/test_symbols.py
- tests/e2e/test_threaded_handlers.py
- tests/test_feature_manager.py
This should allow the subclass of a client/server to be used where the
base class is expected e.g. [source](https://github.com/swyddfa/lsp-devtools/issues/195#issuecomment-2500985890)
``` python
def my_client_factory() -> MyLanguageClient:
client = MyLanguageClient(
converter_factory=default_converter,
)
@client.feature(types.WORKSPACE_CONFIGURATION)
def configuration(client: LanguageClient, params: types.ConfigurationParams):
return [
client.get_configuration(section=item.section, scope_uri=item.scope_uri)
for item in params.items
]
```
This PR also cleans up the deprecation warnings in the test suite raised by `pytest-asyncio`
Closes #515
> Use `issubclass` when checking the client/server instance to inject

- docs/source/pygls/howto/migrate-to-v2.rst
- examples/servers/code_lens.py
- examples/servers/commands.py
- pygls/exceptions.py
- pygls/protocol/json_rpc.py
- pygls/protocol/language_server.py
- tests/e2e/test_commands.py
I *think* this is the last major change I wanted to add to v2! :sweat_smile: 
With this PR *pygls* will now use a handler's type annotations (if available) to automatically convert json arguments into well-defined objects. If the supplied arguments are not compatible with the annotations, an error will automatically be raised.
These type annotations are **not mandatory** and arguments will be given the raw value when an annotation is missing. However, I will not be surprised if there are subtle differences in how handlers are called when compared to the existing behaviour. 
<details>
<summary>Before</summary>
```python
@server.command("codeLens.evaluateSum")
def evaluate_sum(ls: LanguageServer, args):
logging.info("arguments: %s", args)
arguments = args[0]
document = …
```
> Use type annotations when invoking `@server.command(...)` handlers

- examples/hello-world/main.py
The v2.0 introduce some syntax breaking changes. When I tried running the included `hello-world` example, it broke. I had to update the syntax to get it working.
> Update the hello world example to the v2.0 syntax

- poetry.lock
- pyproject.toml
- tests/pyodide/package-lock.json
- tests/pyodide/package.json
This PR should fix the pyodide test suite - as well as bumping the version of pyodide we test to the latest.
The issue came down to dependency resolution... (something that I think has bitten us before?). The version of `attrs` available [by default](https://github.com/pyodide/pyodide/blob/28fcc1bf138732e62e7bbc926ea70a0f13149f54/packages/attrs/meta.yaml#L3) in pyodide was too old relative to the version of `cattrs` being selected by `micropip`.
(`cattrs` was attempting to import `attrs.NothingType` which was only introduced in `attrs v24.3.0`) 
I would have assumed that the [version bound](https://github.com/python-attrs/cattrs/commit/d987382fba782fbe3fea012575cc3c8afbe45481#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R43) on `attrs` supplied by `cattrs` itself …
> Fix pyodide tests

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/tools.mk
- Makefile
Feel free to close this, but I am wondering if we'd be interested in adding a [devcontainer](https://containers.dev/) definition and some Makefile rules to the repo?
`pygls` is "just" a normal, pure Python library and so has fairly minimal requirements in terms of a development environment. But throw in the `pygls-playground` extension, pyodide test suite (and hopefully soon<sup>TM</sup>, a wasm-wasi test suite) and the list of requirements quickly starts to grow.
The provided `Makefile` aims to take you from a clean git clone to up and running in just a couple of commands. The only prerequisites being git, make, curl and a few other standard unix tools.
Some notes on the overall approach
- The devcontainer is **entirely optional**, it is there for people who like that approach and …
> chore: add devcontainer definition and Makefile

- pygls/workspace/position_codec.py
- pygls/workspace/text_document.py
- tests/test_document.py
The `PositionCodec` does not need a mutable sequence as it only does read-only operations. Additionally, `TextDocument.lines` can now return an immutable list (using tuple here for simplicity), which will enable `pygls` to cache the `lines` attribute later internally.
The caching is not done in this commit as it would require us to figure out the cache invalidation rules, which will be after this has been accepted.
See #551
```sh
```
> Make `TextDocument.lines` be a `Sequence[str]` rather than `List[str]`

- .devcontainer/devcontainer.json
- .devcontainer/tools.mk
- Makefile
- pyproject.toml
- tests/conftest.py
Building on #561, now that we're using `uv` directly for everything we're not only able to simply the Makefile greatly, but it's now trivial to switch between Python versions.
By default, the Makefile will use 3.13
```
$ make test
/home/alex/.local/bin/uv run --managed-python --python 3.13 --group test --all-extras poe test
Poe => pytest --cov
=========================================================== test session starts ===========================================================
platform linux -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0
```
But by setting the `PY` variable when running make, you easily test against a different version, say 3.9
```
$ PY=3.9 make test
/home/alex/.local/bin/uv run --managed-python --python 3.9 --group test --all-extras poe test
Using CPython 3.9.23 …
```
> Update Makefile to easily switch between Python versions

- pygls/workspace/position_codec.py
- tests/test_document.py
`didChange` events coming from a client which prefers UTF-8 position encoding (Helix in my case) and includes multi-byte codepoints previously resulted in inconsistency between the client's view of the document and a pygls-based server's view of it as maintained by the `LanguageServerProtocol.lsp_text_document__did_change` -> `Workspace.update_text_document` -> `TextDocument.apply_change` -> `TextDocument._apply_incremental_change`.
For example, opening a document with the contents `öbc` and inserting an `a` to make it into `öabc` would result in pygls thinking the contents are `öbac`.
This PR introduces tests that show the issue, fixes them, and adjusts some incorrect tests that are broken by the fix.
```sh
uv run --all-extras poe …
```
> Fix UTF-8 position encoding

- pygls/protocol/json_rpc.py
`_send_data` method catches any exception and calls `report_server_error` method that tries to notify client. But the connection to the client is lost. It cause the infinite exception loop.
> fix: Handle a special case of BrokenPipeError exception 

- .github/workflows/json-extension.yml
- .vscode/extensions/pygls-playground/Makefile
- .vscode/extensions/pygls-playground/package-lock.json
- .vscode/extensions/pygls-playground/package.json
- .vscode/extensions/pygls-playground/src/extension.ts
- .vscode/settings.json
- Makefile
- pyproject.toml
This allows the user to specify an arbitrary command to use when launching the python interpreter. When combined with tools like `uv`, this makes it trivial to switch between different versions of pygls!
For example
```json
{
"pygls.server.pythonCommand": ["uv", "run", "--no-project", "--prerelease=allow", "--with", "pygls==2.0a2", "python"]
}
```
```sh
uv run --all-extras poe lint
```
> Change `pythonPath` to `pythonCommand` in the `pygls-playground` extension

- pygls/capabilities.py
- tests/test_feature_manager.py
The textDocument/InlineCompletion feature was not being properly announced as a server capability.
```sh
uv run --all-extras poe lint
```
> fix: missing inline completion provider server capability
